### ISSUE TITLE
training

### ISSUE THREAD

**Issue by huangmengxiao000** [frederickszk/LRNet#24]
Hello, I saw in the article that each video is divided into segments with a fixed length of 60, and when the FPS is 30, the sum of these segments is 2 seconds. How to set this up in code.

**Comment by frederickszk** [comment]
You can modify this setting at:
https://github.com/frederickszk/LRNet/blob/408f28881e2864e8d731143849abf56f961ddefa/training/configs/args_train.yaml#L1
If you change the segment length in train-setting, using the same length in the test-setting would have better results:
https://github.com/frederickszk/LRNet/blob/408f28881e2864e8d731143849abf56f961ddefa/training/configs/args_test.yaml#L1

---

The setting of 60 frames reported in the artical might be out-of-date. Our subsequent experiments found that 30 frames could reach slightly better performance.

**Comment by huangmengxiao000** [comment]
If set to 60, do other hyperparameters need to be changed？

**Comment by huangmengxiao000** [comment]
Also, it is used during test evaluation. For example, if a video has 303 frames, it will be cut into 10 samples (each sample contains 30 consecutive frames), and the last 3 frames will be discarded. Is there such a rule?

**Comment by frederickszk** [comment]
> If set to 60, do other hyperparameters need to be changed？

None of the other hyperparameters need to be changed.

> Also, it is used during test evaluation. For example, if a video has 303 frames, it will be cut into 10 samples (each sample contains 30 consecutive frames), and the last 3 frames will be discarded. Is there such a rule?

Yes, the codes
https://github.com/frederickszk/LRNet/blob/408f28881e2864e8d731143849abf56f961ddefa/training/evaluate.py#L61
would handle it.
