### ISSUE TITLE
Strange request for you

### ISSUE THREAD

**Issue by DalvikPip** [frederickszk/LRNet#30]
Hello. I have a rather strange request for you. May I ask you to remove training/model_tf.py and other references to TensorFlow from your repository for one week?
It is quite difficult for me to explain why I need this, but it will help me a lot in my studies.

**Comment by frederickszk** [comment]
Hello. I would be happy to help you out, but recently I may not have the enough time to maintain this repo and make adjustments to files and documentation. I might only be able to attend to it around June 10th. Is that still okay for you ?

**Comment by DalvikPip** [comment]
I don't need it anymore.  Please forgive me for disturbing you 👉👈
