### ISSUE TITLE
FF++和Celeb-DF数据集问题

### ISSUE THREAD

**Issue by 010108** [frederickszk/LRNet#34]
学长你好，请问您那还有没有FF++和Celeb-DF数据集视频提取的人脸帧图片，如果有的话能不能给我发一份，我的邮箱是mhuan108@163.com

**Comment by frederickszk** [comment]
> 学长你好，请问您那还有没有FF++和Celeb-DF数据集视频提取的人脸帧图片，如果有的话能不能给我发一份，我的邮箱是[mhuan108@163.com](mailto:mhuan108@163.com)

你好！我这边本地没存单帧的人脸，因为图片数据集太大了hh
推荐用 [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) 来处理，下载运行后设定好输出参数，在文件夹选中所有视频开始处理就好，很方便。输出的是已经经过alignment的单帧图片，并且会按照视频名称存储在各个文件夹中。

**Comment by 010108** [comment]
好哒，谢谢学长

**Comment by karchen-geng** [comment]
> 学长你好，请问您那还有没有FF++和Celeb-DF数据集视频提取的人脸帧图片，如果有的话能不能给我发一份，我的邮箱是[mhuan108@163.com](mailto:mhuan108@163.com)

您好，请问您那有处理好的数据集了嘛？
